
spring:
  profiles: pro

  #ssdb config
  ssdb:
    master:
      host: 192.168.168.1
      port: 8888
    slave:
      host: 192.168.168.2
      port: 8888
    timeout: 3000
    pool:
      maxIdle: 8
      minIdle: 0
      maxActive: 10
      maxWait: -1
      whenExhaustedAction: 1
      testOnBorrow: false
      testOnReturn: false
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: -1


  #master or slave host port
  slaveof: 
    zk:
      addr: 192.168.*.*:2181
      root: dataware-dev/monitor
      # 重试策略 最大重试次数
      max: 3
      sleep: 5000
      #连接超时时间
      connection: 5000
      #会话超时时间
      session: 3600

  # mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/complain?useUnicode=true&characterEncoding=utf-8
    username: root
    passowrd: 123456
    primary:
      max-idle: 10
      max-wait: 1000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
  
